import type { DriverStore } from './types';

export const createMockDriverStore = (): DriverStore => ({
  driver: {
    id: 'DRV-NER-2048',
    name: 'Aarav Das',
    phone: '+91 98640 21874',
    email: 'aarav.das@smartner.dev',
    accountStatus: 'Active',
  },
  vehicle: {
    id: 'NER-TRK-48',
    type: 'Medium-duty cargo truck',
    registration: 'AS 01 TR 4821',
    operationalStatus: 'Ready',
    lastInspection: '28 Aug 2026',
  },
  activeTripId: 'trip-0418',
  location: {
    status: 'idle',
    message: 'Location is off until you request it.',
  },
  isOnline: typeof navigator === 'undefined' ? true : navigator.onLine,
  sosActive: false,
  disruptions: [
    {
      id: 'disruption-flood-01',
      type: 'Flooding',
      severity: 'warning',
      location: 'NH-15, near Koliabhomora bridge approach',
      distanceAheadKm: 8,
      reportedAt: '12 min ago',
      status: 'Active',
      impact: 'Waterlogging is slowing heavy vehicles. Use the recommended diversion if the crossing closes.',
    },
  ],
  alerts: [
    {
      id: 'alert-001',
      severity: 'warning',
      title: 'Flooding reported 8 km ahead',
      message: 'Waterlogging is affecting the NH-15 bridge approach on your planned route.',
      timestamp: '12 min ago',
      location: 'Koliabhomora bridge approach',
      tripId: 'trip-0418',
      read: false,
      action: 'review_route',
    },
    {
      id: 'alert-002',
      severity: 'information',
      title: 'Vehicle readiness confirmed',
      message: 'NER-TRK-48 passed its scheduled readiness check.',
      timestamp: '2 h ago',
      read: true,
    },
  ],
  reports: [],
  trips: [
    {
      id: 'trip-0418',
      shipmentId: 'SNL-26002-0418',
      commodity: 'Temperature-sensitive medical supplies',
      origin: { name: 'Guwahati Logistics Hub', detail: 'Kamrup Metropolitan, Assam' },
      destination: { name: 'Tezpur Regional Depot', detail: 'Sonitpur, Assam' },
      status: 'ready',
      priority: 'Priority',
      scheduledFor: 'Today, 09:30',
      progressPercent: 0,
      selectedRouteId: 'route-nh15',
      disruptionIds: ['disruption-flood-01'],
      routeOptions: [
        {
          id: 'route-nh15',
          name: 'NH-15 corridor',
          distanceKm: 182,
          etaMinutes: 255,
          risk: 'moderate',
          accessibility: 'Monitor',
          note: 'Current planned route; flooding reported near the bridge approach.',
        },
        {
          id: 'route-diversion',
          name: 'North bank diversion',
          distanceKm: 198,
          etaMinutes: 278,
          risk: 'low',
          accessibility: 'Clear',
          note: 'Development recommendation based on the active disruption scenario.',
          recommended: true,
        },
        {
          id: 'route-hill',
          name: 'Hills connector',
          distanceKm: 174,
          etaMinutes: 295,
          risk: 'high',
          accessibility: 'Restricted',
          note: 'Shorter distance, but steeper road sections and lower accessibility.',
        },
      ],
    },
    {
      id: 'trip-0421',
      shipmentId: 'SNL-26002-0421',
      commodity: 'Packaged food supplies',
      origin: { name: 'Jorhat Distribution Point', detail: 'Jorhat, Assam' },
      destination: { name: 'Dhemaji Supply Hub', detail: 'Dhemaji, Assam' },
      status: 'assigned',
      priority: 'Standard',
      scheduledFor: 'Tomorrow, 07:00',
      progressPercent: 0,
      selectedRouteId: 'route-a',
      disruptionIds: [],
      routeOptions: [
        { id: 'route-a', name: 'NH-15 eastbound', distanceKm: 146, etaMinutes: 214, risk: 'low', accessibility: 'Clear', note: 'Scheduled route.' },
      ],
    },
    {
      id: 'trip-0394',
      shipmentId: 'SNL-26002-0394',
      commodity: 'Agricultural equipment',
      origin: { name: 'Nagaon Freight Yard', detail: 'Nagaon, Assam' },
      destination: { name: 'Guwahati Logistics Hub', detail: 'Kamrup Metropolitan, Assam' },
      status: 'completed',
      priority: 'Standard',
      scheduledFor: '27 Aug 2026',
      completedAt: '27 Aug 2026, 16:42',
      proofOfDelivery: 'Recorded locally',
      progressPercent: 100,
      selectedRouteId: 'route-complete',
      disruptionIds: [],
      routeOptions: [
        { id: 'route-complete', name: 'NH-27 westbound', distanceKm: 122, etaMinutes: 186, risk: 'low', accessibility: 'Clear', note: 'Completed route.' },
      ],
    },
  ],
});
