import { CheckCircle2, ClipboardCheck, History, Radio, RefreshCw, Truck, UserRound, WifiOff } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useDriver } from '../DriverContext';

export const ProfileScreen = () => {
  const { store, syncPendingReports } = useDriver();
  const completed = store.trips.filter((trip) => trip.status === 'completed');
  const pendingReports = store.reports.filter((report) => report.syncState === 'pending' || report.syncState === 'failed' || report.syncState === 'syncing');
  return <div className="screen-stack"><header className="screen-heading"><p className="eyebrow">Driver account</p><h1>Profile & history</h1><p className="heading-copy">Useful driver, vehicle, local-sync, and delivery details in one place.</p></header>
    <div className="profile-grid"><section className="profile-card card"><div className="profile-avatar"><UserRound size={31} /></div><h2>{store.driver.name}</h2><span className="status-chip ready">{store.driver.accountStatus}</span><dl className="detail-list"><div><dt>Driver ID</dt><dd>{store.driver.id}</dd></div><div><dt>Phone</dt><dd>{store.driver.phone}</dd></div><div><dt>Email</dt><dd>{store.driver.email}</dd></div></dl></section>
      <section className="vehicle-profile card"><div className="card-heading"><div><p className="eyebrow">Assigned vehicle</p><h2>{store.vehicle.id}</h2></div><Truck size={22} /></div><p>{store.vehicle.type}</p><dl className="detail-list"><div><dt>Registration</dt><dd>{store.vehicle.registration}</dd></div><div><dt>Operational status</dt><dd>{store.vehicle.operationalStatus}</dd></div><div><dt>Last readiness check</dt><dd>{store.vehicle.lastInspection}</dd></div></dl></section></div>
    <section className="sync-card card"><div><div className="card-heading"><div><p className="eyebrow">Offline & sync foundation</p><h2>{store.isOnline ? 'Connected device' : 'Offline mode'}</h2></div>{store.isOnline ? <Radio size={21} /> : <WifiOff size={21} />}</div><p>{pendingReports.length ? `${pendingReports.length} report${pendingReports.length === 1 ? '' : 's'} ${pendingReports.some((report) => report.syncState === 'syncing') ? 'syncing' : 'queued'} locally.` : 'No report is waiting in the local queue.'} This development build intentionally has no remote sync endpoint.</p></div><button className="button secondary" type="button" disabled={!store.isOnline || !pendingReports.length} onClick={syncPendingReports}><RefreshCw size={17} />{pendingReports.some((report) => report.syncState === 'syncing') ? 'Syncing…' : 'Retry local sync'}</button></section>
    {store.reports.length > 0 && <section className="card local-reports"><div className="section-label"><p className="eyebrow">Local observations</p><h2>Saved incident reports</h2></div>{store.reports.map((report) => <div className="local-report" key={report.id}><span className={`status-chip ${report.syncState === 'pending' ? 'delayed' : 'ready'}`}>{report.syncState === 'synced' ? 'Saved locally' : report.syncState}</span><div><strong>{report.type}</strong><p>{report.locationLabel} · {report.createdAt}</p></div></div>)}</section>}
    <section className="history-section" aria-labelledby="history-title"><div className="section-label"><p className="eyebrow">Delivery history</p><h2 id="history-title">Completed trips</h2></div>{completed.length ? <div className="history-list">{completed.map((trip) => <Link className="history-row card" to={`/driver/trips/${trip.id}`} key={trip.id}><span className="history-icon"><CheckCircle2 size={19} /></span><div><strong>{trip.shipmentId}</strong><p>{trip.origin.name} → {trip.destination.name}</p></div><div><small>Completed</small><strong>{trip.completedAt}</strong></div><div><small>Distance</small><strong>{trip.routeOptions.find((route) => route.id === trip.selectedRouteId)?.distanceKm} km</strong></div></Link>)}</div> : <section className="empty-state card"><History size={27} /><h2>No delivery history yet</h2><p>Complete an in-progress delivery to record it here.</p></section>}</section>
    <section className="profile-note card"><ClipboardCheck size={20} /><p>Personal information is limited to operational details shown in this development workspace.</p></section>
  </div>;
};
